### ISSUE TITLE
OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by anapaulagomes** [FussyFox/black#5]
Just got this error. Can you check if Black is running please? That's the only linter I'm having trouble. Thanks!

**.checks.yml**
```
- flake8
- black
- pyflakes
- bandit
```

**Traceback**
```
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/var/lang/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/task/black.py", line 3511, in <module>
    main()
  File "/var/task/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/task/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/task/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/task/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/task/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/task/black.py", line 341, in main
    executor = ProcessPoolExecutor(max_workers=os.cpu_count())
  File "/var/lang/lib/python3.6/concurrent/futures/process.py", line 390, in __init__
    EXTRA_QUEUED_CALLS)
  File "/var/lang/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/var/lang/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented
```

https://github.com/anapaulagomes/pytest-picked/pull/10/checks?check_run_id=6783424

**Comment by codingjoe** [comment]
@anapaulagomes I believe this is related to the issue on flake8 here
https://github.com/LambdaLint/flake8/commit/0661aa58becf5c6137c240cc53191f5f18b83de1

Essentially, you can't use multiprocessing on AWS lambda, since it doesn't support mp syncronization.

**Comment by anapaulagomes** [comment]
Got it. I don't think Black supports subprocesses at this moment. :(

**Comment by codingjoe** [comment]
@anapaulagomes good point, they don't support overriding it. I opened an issue. Let's see how it progresses.

**Comment by codingjoe** [comment]
Looks like we need to walk the file tree ourselfes and make alles the calls for each file individually...

**Comment by codingjoe** [comment]
Seems like there is nothing we can do, except running the linter for each file individually, which I am not a fan of, seealso https://github.com/ambv/black/issues/421
